### ISSUE TITLE
[BUG] ForecastingAnomalyModel produces endless messages while fitting even after max_epochs reached

### ISSUE THREAD

**Issue by thuyng-ing** [unit8co/darts#1982] opened 2023-09-06 14:38 UTC
**Describe the bug**

ForecastingAnomalyModel displayed this message below endlessly when fitting even after `Trainer.fit` stopped: `max_epochs=2` reached.

```
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]
GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
HPU available: False, using: 0 HPUs
```

**To Reproduce**
Steps to reproduce the behavior, preferably code snippet.

```
from darts.models import RNNModel

forecasting_model = RNNModel(
    model="RNN",
    hidden_dim=20,
    dropout=0,
    batch_size=16,
    n_epochs=2,
    optimizer_kwargs={"lr": 1e-3},
    model_name="RNN",
    log_tensorboard=True,
    random_state=42,
    training_length=20,
    input_chunk_length=48,
    force_reset=True,
)
```

```
from darts.ad import ForecastingAnomalyModel, NormScorer, WassersteinScorer

half_a_day = 2 * 12
full_day = 2 * 24

anomaly_model = ForecastingAnomalyModel(
    model=forecasting_model,
    scorer=[
        NormScorer(ord=1),
        WassersteinScorer(window=half_a_day),
        WassersteinScorer(window=full_day),
    ],
)

START = 0.1
anomaly_model.fit(train, start=START, allow_model_training=True)
```

**Expected behavior**

The message below is displayed repeatedly and endlessly.
```
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]
GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
HPU available: False, using: 0 HPUs
```

**System (please complete the following information):**
 - Python version: 3.9
 - darts version: 0.23.0

**Comment by thuyng-ing** [comment] 2023-09-19 10:02
May I ask if there is any update on this? @madtoinou

**Comment by madtoinou** [comment] 2023-09-19 10:53
Hi @thuyng-ing,

Sorry for not coming back at you, this issue was added to the backlog, we will make sure to include it in the next release.

**Comment by thuyng-ing** [comment] 2023-09-19 11:13
May I ask when the next release is expected? Thanks!

**Comment by madtoinou** [comment] 2023-09-19 12:14
We are aiming for end of October, beginning of November but it might change based on our capacity.

**Comment by madtoinou** [comment] 2023-10-30 07:59
Hi @thuyng-ing,

I just checked with the master branch using the `AirPassengerDataset` as training series and could not reproduce the bug. The message appears twice: once when training the model, another time when fitting the anomaly model, as expected.

I am going to close this for now, feel free to reopen if the problem persists after updating darts to the latest version.

**Closed by madtoinou** 2023-10-30 07:59 UTC
Labels: bug
