### ISSUE TITLE
`historical_forecasts()` need large memory?

### ISSUE THREAD

**Issue by Syy-99** [unit8co/darts#1869] opened 2023-06-29 13:11 UTC
The code is as follows:

```python
"""
this is my RNN Model:
    model = RNNModel (
        model="LSTM",
        hidden_dim=20,     
        batch_size=16,
        n_epochs=200,      
        optimizer_kwargs={"lr": 1e-4},  
        model_name="lstm_{}_{}_real".format(my_output_chunk_length,work_load_name),
        log_tensorboard=True,
        random_state=42,
        training_length = my_train_length,    # my_train_length = 30
        input_chunk_length = my_train_length,  # my_train_length = 30
        save_checkpoints=True,     
        pl_trainer_kwargs={"accelerator": "gpu", "devices": [0] }
    )
"""
# load the model
model = RNNModel.load_from_checkpoint("lstm_{}_{}_real".format(my_output_chunk_length,work_load_name), best = True)
# prediction
start_time = time.time()
prediction_value = model.historical_forecasts(
    data, start = pd.Timestamp("2007-09-24 00:00:00")
    retrain = False,
    # verbose = True,
    forecast_horizon=my_output_chunk_length,  # my_output_chunk_length = 1
    last_points_only=False  
)
```

When I run this code, I found that the memory occupied by the program is gradually increasing, and finally the program outputs `killed`.
I'm sure that no other program is taking up too much memory when I run this code, and that I have at least 16G of memory available when I run it

I don't know if it's the size of the data, because `data` has about 1 million rows of data, and there are about 600,000 data that need to be predicted after `start`.
`data`  file is like this:
```
2007-09-19 04:10:43,148
2007-09-19 04:10:44,872
...
```
Or what settings do I need to make to avoid this problem?
（I'm guessing it's because `historical_forecasts()` loads all the data into memory?But I think that each prediction should only need to load the data of `my_train_length length`, and should not require so much memory）

**Comment by madtoinou** [comment] 2023-07-07 07:41
Hi @Syy-99,

Since you called `historical_forecasts()` with `last_points_only=False`, the method incrementally build a list containing all the forecasted TimeSeries. In your case, 600'000 ts of length 1.

Furthermore, `historical_forecasts()` is not well optimized at the moment and creates a duplicate of the data to run training/prediction (to adjust the end timestamp). It would probably be possible to adjust the start timestamp and obtain something of length `input_chunk_length` to reduce memory footprint.

The two points mentioned above, plus the space taken by the model itself, might explain the high memory consumption and program termination.

Optimizing `historical_forecasts` is at the top of the backlog, if you have time to experiment and clearly identify the bottlenecks, it would be amazing.

**Closed** 2023-07-12 02:25 UTC
