### ISSUE TITLE
Extend crossvalidation with historical_forecast and backtest for global models

### ISSUE THREAD

**Issue by TobiasBraeutigam** [unit8co/darts#1302] opened 2022-10-20 08:48 UTC
I would like to use crossvalidation (historical_forecast and backtest) with global-models on multi-target series.

Currently I can only apply those functions on one single series like this:
model.backtest(series=series_target_a). 

But I would like to do this for multi-target scenarios aswell:
result = model.backtest(series=[series_target_a, series_target_b]).

If I applied model.backtest(reduction=None) result[0] gives me all scores for target_a and result[1] gives me all scores for target_b.
Otherwise result[0] gives me one aggregated score for target_a.

This would allow a more realistic cross-validation for multi-target-models as in an productive environment I would use them every day/week/month like this instead of training and applying them on only one series at a time.

global_model.fit(series=[series_target_a, series_target_b])
pred_list = global_model.predict(series=[series_target_a, series_target_b])

Keep up the great work you are doing here!

Best regards,
Tobias

**Comment by dennisbader** [comment] 2022-10-27 06:41
Sorry for the late response!

I will close this as it's currently being worked on (duplicate of #1293).

**Closed** 2022-10-27 06:41 UTC
Labels: triage
