### ISSUE TITLE
Fit model before historical forecast method?

### ISSUE THREAD

**Issue by ETTAN93** [unit8co/darts#1639] opened 2023-03-09 21:38 UTC
Do I actually need to fit the model before implementing the historical forecast method? From what I understand, even if you do not fit the model, if retrain is set to False, the historical forecast method already fits the model once. 

However, if I do not fit the model before historical forecast, I notice that setting retrain = False or setting retrain = True makes no difference in the speed of the method. If I do fit the model before, then it makes a difference.

Is that expected?

**Comment by madtoinou** [comment] 2023-03-10 08:29
Hi,

This is a duplicate of #1617, it is the expected behavior introduced by #1465 to avoid mutating the underlying model object. You indeed should `fit()` the model before using `historical_forecasts`.

The model gets retrained because it was not fit before (Darts requires the models to be fit before prediction), regardless of the `retrain` argument value.

**Closed by madtoinou** 2023-03-10 08:29 UTC
Labels: bug, triage

**Comment by ETTAN93** [comment] 2023-03-13 17:58
@madtoinou thanks for letting me know. just to be sure I got the methodology right, do I fit on the entire dataset that I have before doing historical forecast or do I only fit on the training set, i.e. between start_date and split_date, that is used by the historical forecast?
