### ISSUE TITLE
[BUG] Install from conda but unable to import modules

### ISSUE THREAD

**Issue by GregoryCrysler** [unit8co/darts#1677] opened 2023-03-28 20:33 UTC
**Describe the bug**
After creating a fresh environment for darts v 0.23.1, unable to load darts modules.  The following error is produced:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\User\.conda\envs\mini-base-test-v023\lib\site-packages\darts\__init__.py", line 8, in <module>
    import matplotlib as mpl
  File "C:\Users\User\.conda\envs\mini-base-test-v023\lib\site-packages\matplotlib\__init__.py", line 107, in <module>
    from . import _api, cbook, docstring, rcsetup
  File "C:\Users\User\.conda\envs\mini-base-test-v023\lib\site-packages\matplotlib\rcsetup.py", line 24, in <module>
    from matplotlib import _api, animation, cbook
  File "C:\Users\User\.conda\envs\mini-base-test-v023\lib\site-packages\matplotlib\animation.py", line 34, in <module>
    from PIL import Image
  File "C:\Users\User\.conda\envs\mini-base-test-v023\lib\site-packages\PIL\Image.py", line 103, in <module>
    from . import _imaging as core
ImportError: DLL load failed while importing _imaging: The specified module could not be found.

**To Reproduce**
conda create --name mini-base-test-v023 python=3.9
conda activate mini-base-test-v023
conda install -c conda-forge -c pytorch u8darts-all=0.23.1

>>> from darts.dataprocessing.transformers import Scaler

**Expected behavior**
Scaler is loaded without issue.

**System (please complete the following information):**
 - Python version: 3.9
 - darts version :0.23.1

**Additional context**
I've attached the output for conda list.  If I'm missing something easy, kindly let me know.
[CondaList_032823.txt](https://github.com/unit8co/darts/files/11093919/CondaList_032823.txt)

**Comment by madtoinou** [comment] 2023-04-04 12:41
The error seems to come from the PIL module, a dependency of matplotlib, suggesting that the problem might come from  the distribution of these libraries by conda.

Can you try to create a environment with conda but install the darts library using pip?
```bash
conda create --name darts-latest python=3.9
conda activate darts-latest
pip install darts
```

**Comment by madtoinou** [comment] 2023-11-02 11:22
Closing this issue since as detailed instructions are available in the documentation and could not reproduce the problem.

**Closed by madtoinou** 2023-11-02 11:22 UTC
Labels: bug, devops
