### ISSUE TITLE
[BUG] Docker images does not run examples

### ISSUE THREAD

**Issue by mosheliv** [unit8co/darts#497] opened 2021-10-03 22:28 UTC
**Describe the bug**
Docker image can't run NBEATS example (probably all the examples)

**To Reproduce**
./gradlew docker, ./gradlew dockerRun the docker image starts but trying to run the NBEATS example gives on cell 8 (model_nbeats.fit(train, val_series=val, verbose=True)) the following:
```
---------------------------------------------------------------------------
PermissionError                           Traceback (most recent call last)
/tmp/ipykernel_44/300047873.py in <module>
----> 1 model_nbeats.fit(train, val_series=val, verbose=True)

~/work/darts/utils/torch.py in decorator(self, *args, **kwargs)
     63         with fork_rng():
     64             manual_seed(self._random_instance.randint(0, high=MAX_TORCH_SEED_VALUE))
---> 65             return decorated(self, *args, **kwargs)
     66     return decorator

~/work/darts/models/forecasting/torch_forecasting_model.py in fit(self, series, past_covariates, future_covariates, val_series, val_past_covariates, val_future_covariates, verbose, epochs)
    429         logger.info('Train dataset contains {} samples.'.format(len(train_dataset)))
    430 
--> 431         self.fit_from_dataset(train_dataset, val_dataset, verbose, epochs)
    432 
    433     @random_method

~/work/darts/utils/torch.py in decorator(self, *args, **kwargs)
     63         with fork_rng():
     64             manual_seed(self._random_instance.randint(0, high=MAX_TORCH_SEED_VALUE))
---> 65             return decorated(self, *args, **kwargs)
     66     return decorator

~/work/darts/models/forecasting/torch_forecasting_model.py in fit_from_dataset(self, train_dataset, val_dataset, verbose, epochs)
    473             # Build model, based on the dimensions of the first series in the train set.
    474             self.train_sample, self.output_dim = train_sample, train_sample[-1].shape[1]
--> 475             self._init_model()
    476         else:
    477             # Check existing model has input/output dims matching what's provided in the training set.

~/work/darts/models/forecasting/torch_forecasting_model.py in _init_model(self)
    282             self.lr_scheduler = None  # We won't use a LR scheduler
    283 
--> 284         self._save_untrained_model(_get_untrained_models_folder(self.work_dir, self.model_name))
    285 
    286     @abstractmethod

~/work/darts/models/forecasting/torch_forecasting_model.py in _save_untrained_model(self, folder)
    894 
    895     def _save_untrained_model(self, folder):
--> 896         os.makedirs(folder, exist_ok=True)
    897         filename = os.path.join(folder, 'model.pth.tar')
    898 

/opt/conda/lib/python3.9/os.py in makedirs(name, mode, exist_ok)
    213     if head and tail and not path.exists(head):
    214         try:
--> 215             makedirs(head, exist_ok=exist_ok)
    216         except FileExistsError:
    217             # Defeats race condition when another thread created the path

/opt/conda/lib/python3.9/os.py in makedirs(name, mode, exist_ok)
    213     if head and tail and not path.exists(head):
    214         try:
--> 215             makedirs(head, exist_ok=exist_ok)
    216         except FileExistsError:
    217             # Defeats race condition when another thread created the path

/opt/conda/lib/python3.9/os.py in makedirs(name, mode, exist_ok)
    223             return
    224     try:
--> 225         mkdir(name, mode)
    226     except OSError:
    227         # Cannot rely on checking for EEXIST, since the operating system

PermissionError: [Errno 13] Permission denied: '/home/jovyan/work/examples/.darts'
```

**Expected behavior**
it should run!

**System (please complete the following information):**
its a docker so you should have the same image

**Additional context**

**Comment by mosheliv** [comment] 2021-10-04 20:07
While you revise the dockerfile, you might want to switch to a somewhat
less personal pathnames... Usually /work is the standard.

**Comment by Loudegaste** [comment] 2022-12-14 15:48
It's an old issue but as of end 2022, I can't reproduce it. It works fine locally (slow but it works). Unless someone can reproduce it, maybe we should close the issue.

**Comment by hrzn** [comment] 2023-01-05 10:15
Thanks @Loudegaste, closing.

**Closed by hrzn** 2023-01-05 10:15 UTC
Labels: bug, good first issue
