### ISSUE TITLE
[Question] - Install Darts without use of PIP

### ISSUE THREAD

**Issue by jnews5** [unit8co/darts#348] opened 2021-06-16 15:50 UTC
Hello,

Bit a silly question but is there a guide on how to install Darts without the use of PIP? I don't see Darts able to be installed using conda install so a manual install instruction is appreciated.

**Comment by pennfranc** [comment] 2021-06-24 14:06
Hey @jnews5, currently we only recommend installing Darts using pip. Adding the possibility to install Darts using conda is on our roadmap, but as you noticed this is currently not supported.

**Comment by hrzn** [comment] 2021-07-10 13:20
Duplicate of https://github.com/unit8co/darts/issues/136

**Closed by hrzn** 2021-07-10 13:20 UTC
Labels: duplicate

**Comment by tomasvanpottelbergh** [comment] 2021-08-03 09:53
@jnews5 please see the update [here](https://github.com/unit8co/darts/issues/136#issuecomment-891703175). It would be great if you could test the packages and report any issues there.
