### ISSUE TITLE
Weibull distribution

### ISSUE THREAD

**Issue by hberande** [unit8co/darts#2012] opened 2023-09-29 11:13 UTC
I got ValueError: Expected parameter scale (Tensor of shape (32, 96, 1)) of distribution Weibull(scale: torch.Size([32, 96, 1]), concentration: torch.Size([32, 96, 1])) to satisfy the constraint GreaterThan(lower_bound=0.0), but found invalid values:tensor([[[ 3.9661e-30],[ 1.2568e+01],[ 6.9787e-08]........while using Weibull likelihood parameter but the input was given while using Laplace and Gaussian Likelihood & code was run successfully.

**Comment by madtoinou** [comment] 2023-10-16 07:09
Hi @hberande,

This is a duplicate of #1813, the error message indicates that some of the model's output are not in the distribution support (most likely during the training).

**Closed by madtoinou** 2023-10-16 07:09 UTC
