### ISSUE TITLE
Cannot get optuna gridSearch to work. TypeError: Unknown type of parameter:series, got:TimeSeries

### ISSUE THREAD

**Issue by Allena101** [unit8co/darts#2119] opened 2023-12-13 10:23 UTC
I am following your guides on optuna and Ray tune. With ray tune i keep getting time out error and dont know why , but i will start asking about optuna. I want to use lightgbm (as i understand it , any model in darts , i should be able to use). Will ask about optuna since i did manage to get it to work some time ago with tensorflow.

I am testing such a simple model as possible just to see if it works and then i can make it more complex. Which seems like a good just get a constant torrent of errors either way. 

Here is the code (again following your guide)

ts = TimeSeries.from_dataframe(edfs, 'dt', ['Interval_Sum'])

ts = ts.drop_before(pd.Timestamp("2023-08-30"))

ts_train, ts_val = ts.split_after(pd.Timestamp("2023-10-01"))

# define objective function
def objective(trial):

    max_depth = trial.suggest_categorical("max_depth", [2, 3])
    num_leaves = trial.suggest_categorical("num_leaves", [2, 3])
    lags = trial.suggest_categorical("lags", [3])

    pruner = PyTorchLightningPruningCallback(trial, monitor="val_loss")
    early_stopper = EarlyStopping("val_loss", min_delta=0.001, patience=3, verbose=True)
    callbacks = [pruner, early_stopper]

    pl_trainer_kwargs = {
        "accelerator": "auto",
        "callbacks": callbacks,
    }

    torch.manual_seed(42)

    # build the TCN model
    model = LightGBMModel(
        series=ts_train,
        # metric = rmse,
        forecast_horizon = 3,
        max_depth = max_depth,
        num_leaves = num_leaves,
        lags = lags
        
    )

    # train the model
    model.fit(
        series=ts_train,
        val_series=ts_val,
        # num_loader_workers=num_workers,
    )

    # reload best model over course of training
    model = TCNModel.load_from_checkpoint("tcn_model")

    # Evaluate how good it is on the validation set, using sMAPE
    preds = model.predict(series=train, n=ts_val)
    smapes = smape(ts_val, preds, n_jobs=-1, verbose=True)
    smape_val = np.mean(smapes)

    return smape_val if smape_val != np.nan else float("inf")

# for convenience, print some optimization trials information
def print_callback(study, trial):
    print(f"Current value: {trial.value}, Current params: {trial.params}")
    print(f"Best value: {study.best_value}, Best params: {study.best_trial.params}")

# optimize hyperparameters by minimizing the sMAPE on the validation set
if __name__ == "__main__":
    study = optuna.create_study(direction="minimize")
    study.optimize(objective, n_trials=100, callbacks=[print_callback])
    

when i run type() on my data it says the same as it does in your example, so i dont know what is going on. 

  More of error messege:
  
  
  [W 2023-12-13 11:17:43,700] Trial 0 failed with parameters: {'max_depth': 2, 'num_leaves': 2, 'lags': 3} because of the following error: TypeError('Unknown type of parameter:series, got:TimeSeries').
Traceback (most recent call last):
  File "c:\Users\Magnus\Desktop\code\timeSeries\venvTS\lib\site-packages\optuna\study\_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "C:\Users\Magnus\AppData\Local\Temp\ipykernel_19460\55056152.py", line 40, in objective
    model.fit(
  File "c:\Users\Magnus\Desktop\code\timeSeries\venvTS\lib\site-packages\darts\models\forecasting\lgbm.py", line 267, in fit
    super().fit(
  File "c:\Users\Magnus\Desktop\code\timeSeries\venvTS\lib\site-packages\darts\models\forecasting\regression_model.py", line 1617, in fit
    super().fit(
  File "c:\Users\Magnus\Desktop\code\timeSeries\venvTS\lib\site-packages\darts\models\forecasting\regression_model.py", line 722, in fit
    self._fit_model(
  File "c:\Users\Magnus\Desktop\code\timeSeries\venvTS\lib\site-packages\darts\models\forecasting\regression_model.py", line 1795, in _fit_model
    super()._fit_model(
  File "c:\Users\Magnus\Desktop\code\timeSeries\venvTS\lib\site-packages\darts\models\forecasting\regression_model.py", line 544, in _fit_model
    self.model.fit(training_samples, training_labels, **kwargs)
  File "c:\Users\Magnus\Desktop\code\timeSeries\venvTS\lib\site-packages\lightgbm\sklearn.py", line 895, in fit
    super().fit(X, y, sample_weight=sample_weight, init_score=init_score,
  File "c:\Users\Magnus\Desktop\code\timeSeries\venvTS\lib\site-packages\lightgbm\sklearn.py", line 748, in fit
    self._Booster = train(
  File "c:\Users\Magnus\Desktop\code\timeSeries\venvTS\lib\site-packages\lightgbm\engine.py", line 271, in train
    booster = Booster(params=params, train_set=train_set)
  File "c:\Users\Magnus\Desktop\code\timeSeries\venvTS\lib\site-packages\lightgbm\basic.py", line 2605, in __init__
    train_set.construct()
  File "c:\Users\Magnus\Desktop\code\timeSeries\venvTS\lib\site-packages\lightgbm\basic.py", line 1815, in construct
    self._lazy_init(self.data, label=self.label,
  File "c:\Users\Magnus\Desktop\code\timeSeries\venvTS\lib\site-packages\lightgbm\basic.py", line 1517, in _lazy_init
    params_str = param_dict_to_str(params)
  File "c:\Users\Magnus\Desktop\code\timeSeries\venvTS\lib\site-packages\lightgbm\basic.py", line 294, in param_dict_to_str
    raise TypeError(f'Unknown type of parameter:{key}, got:{type(val).__name__}')
TypeError: Unknown type of parameter:series, got:TimeSeries
[W 2023-12-13 11:17:43,702] Trial 0 failed with value None.

**Comment by madtoinou** [comment] 2023-12-14 08:50
Closing, duplicate of #2121.

**Closed by madtoinou** 2023-12-14 08:50 UTC
Labels: triage
