### ISSUE TITLE
[BUG] RuntimeError: All input tensors must be on the same device. Received cuda:0 and cpu

### ISSUE THREAD

**Issue by chouteag** [unit8co/darts#413] opened 2021-07-26 09:50 UTC
**Describe the bug**
Getting the 'RuntimeError: All input tensors must be on the same device. Received cuda:0 and cpu' when trying to run the example notebook 05-RNN-examples cell 7  line eval_model(my_model)

**To Reproduce**   
eval_model(my_model)

---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-10-f8c4e85dc7ef> in <module>
----> 1 eval_model(my_model)

<ipython-input-9-860026413a55> in eval_model(model)
      1 def eval_model(model):
----> 2     pred_series = model.predict(n=26, covariates=covariates)
      3     plt.figure(figsize=(8,5))
      4     series_transformed.plot(label='actual')
      5     pred_series.plot(label='forecast')

~/anaconda3/envs/dart-time-series/lib/python3.8/site-packages/darts/utils/torch.py in decorator(self, *args, **kwargs)
     63         with fork_rng():
     64             manual_seed(self._random_instance.randint(0, high=MAX_TORCH_SEED_VALUE))
---> 65             return decorated(self, *args, **kwargs)
     66     return decorator

~/anaconda3/envs/dart-time-series/lib/python3.8/site-packages/darts/models/torch_forecasting_model.py in predict(self, n, series, covariates, batch_size, verbose, n_jobs, roll_size, num_samples)
    518         dataset = SimpleInferenceDataset(series, covariates, n, self.input_chunk_length, self.output_chunk_length,
    519                                          self.is_recurrent)
--> 520         predictions = self.predict_from_dataset(n, dataset, verbose=verbose, batch_size=batch_size, n_jobs=n_jobs,
    521                                                 roll_size=roll_size, num_samples=num_samples)
    522         return predictions[0] if called_with_single_series else predictions

~/anaconda3/envs/dart-time-series/lib/python3.8/site-packages/darts/models/torch_forecasting_model.py in predict_from_dataset(self, n, input_series_dataset, batch_size, verbose, n_jobs, roll_size, num_samples)
    619                 for i in range(num_samples):
    620                     if self.is_recurrent:
--> 621                         batch_prediction = self._predict_batch_recurrent_model(n, input_series, cov_future)
    622                     else:
    623                         batch_prediction = self._predict_batch_block_model(n, input_series, cov_future, roll_size)

~/anaconda3/envs/dart-time-series/lib/python3.8/site-packages/darts/models/torch_forecasting_model.py in _predict_batch_recurrent_model(self, n, input_series, cov_future)
    706             # create new input to model from last prediction and current covariates, if available
    707             new_input = (
--> 708                 torch.cat([out[:, -1:, :], cov_future[:, prediction_length - 1:prediction_length, :]], dim=2)
    709                 if cov_future is not None else out[:, -1:, :]
    710             )

**RuntimeError: All input tensors must be on the same device. Received cuda:0 and cpu**

**Expected behavior**
No bug when calling predict

**System (please complete the following information):**
 - Python version: [3.8.10]
 - darts version [0.9.1]
 - torch [1.8.1+cu102]

**Additional context**
Issue with cuda version 11.3 but same issue when installing cuda 10.2 in the virtualenv with a slightly different error message (RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu! (when checking arugment for argument tensors in method wrapper__cat))

**Comment by micronoz** [comment] 2021-08-23 23:29
any workarounds?

**Comment by hrzn** [comment] 2021-08-24 05:24
> any workarounds?

Could you update to Darts 0.10.1 and let us know if you still experience issues?

**Comment by micronoz** [comment] 2021-08-24 15:54
Yeah still experiencing with 0.10.1. I'm using torch version `torch==1.9.0+cu111` and python 3.9.5. and here is the error `  File "/home/nozberkman/projects/transformer-exercise/venv/lib/python3.9/site-packages/darts/utils/torch.py", line 65, in decorator
    return decorated(self, *args, **kwargs)
  File "/home/nozberkman/projects/transformer-exercise/venv/lib/python3.9/site-packages/darts/models/torch_forecasting_model.py", line 431, in fit
    self.fit_from_dataset(train_dataset, val_dataset, verbose, epochs)
  File "/home/nozberkman/projects/transformer-exercise/venv/lib/python3.9/site-packages/darts/utils/torch.py", line 65, in decorator
    return decorated(self, *args, **kwargs)
  File "/home/nozberkman/projects/transformer-exercise/venv/lib/python3.9/site-packages/darts/models/torch_forecasting_model.py", line 519, in fit_from_dataset
    self._train(train_loader, val_loader, tb_writer, verbose, train_num_epochs)
  File "/home/nozberkman/projects/transformer-exercise/venv/lib/python3.9/site-packages/darts/models/torch_forecasting_model.py", line 825, in _train
    validation_loss = self._evaluate_validation_loss(val_loader)
  File "/home/nozberkman/projects/transformer-exercise/venv/lib/python3.9/site-packages/darts/models/torch_forecasting_model.py", line 850, in _evaluate_validation_loss
    output = self._produce_train_output(val_batch[:-1])
  File "/home/nozberkman/projects/transformer-exercise/venv/lib/python3.9/site-packages/darts/models/torch_forecasting_model.py", line 1111, in _produce_train_output
    return self.model(inpt)
  File "/home/nozberkman/projects/transformer-exercise/venv/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/nozberkman/projects/transformer-exercise/venv/lib/python3.9/site-packages/darts/models/transformer_model.py", line 163, in forward
    src = self.encoder(src) * math.sqrt(self.input_size)
  File "/home/nozberkman/projects/transformer-exercise/venv/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/nozberkman/projects/transformer-exercise/venv/lib/python3.9/site-packages/torch/nn/modules/linear.py", line 96, in forward
    return F.linear(input, self.weight, self.bias)
  File "/home/nozberkman/projects/transformer-exercise/venv/lib/python3.9/site-packages/torch/nn/functional.py", line 1847, in linear
    return torch._C._nn.linear(input, weight, bias)
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cpu and cuda:0! (when checking arugment for argument mat2 in method wrapper_mm)`

**Comment by hrzn** [comment] 2021-08-24 20:16
Could you share a snippet of code to reproduce the issue?

**Comment by micronoz** [comment] 2021-08-24 20:42
`def load():
    filename = 'data/data.csv'
    # Read data:
    df_test = pd.read_csv(filename, nrows=100)
    float_cols = [c for c in df_test if df_test[c].dtype ==
                  "float64" and c != 'unix']
    float32_cols = {c: np.float32 for c in float_cols}
    df = pd.read_csv(filename, engine='c', dtype=float32_cols)
    df = df.drop(['date', 'symbol', 'Volume USDT'], axis=1)
    df['unix'] = df['unix'] * 1000000
    series = TimeSeries.from_dataframe(df, time_col='unix')
    return series


def main():
    series = load()
    series_in = series[['close']].drop_before(5)
    series_cov = series[['open', 'high',
                         'low', 'close']].shift(6)
    # Create training and validation sets:
    train_cov, val_cov = series_cov.split_after(10000)
    train_in, val_in = series_in.split_after(10000)
    scaler = Scaler()
    train_in = scaler.fit_transform(train_in)
    val_in = scaler.transform(val_in)
    train_cov = scaler.fit_transform(train_cov)
    val_cov = scaler.transform(val_cov)

    my_model = TransformerModel(
        input_chunk_length=24,
        output_chunk_length=24,
        batch_size=32,
        n_epochs=200,
        d_model=32,
        nr_epochs_val_period=3,
        nhead=16,
        log_tensorboard=True,
        model_name='hiya',
        num_encoder_layers=8,
        num_decoder_layers=8,
        dim_feedforward=512,
        dropout=0.1,
        activation="relu",
        random_state=42,
        force_reset=True
    )

    my_model.fit(series=train_in, val_series=val_in,
                 past_covariates=train_cov, val_past_covariates=val_cov, verbose=True)

main()`

**Comment by owoshch** [comment] 2021-08-31 11:03
Hi! I've faced the same error while training a RNNModel. Have you solved the issue?

**Comment by micronoz** [comment] 2021-08-31 15:03
> Hi! I've faced the same error while training a RNNModel. Have you solved the issue?

Yes, see the PR related to this issue.

**Comment by owoshch** [comment] 2021-08-31 16:18
> > Hi! I've faced the same error while training a RNNModel. Have you solved the issue?
> 
> Yes, see the PR related to this issue.

Thank you for the reply! I see the PR. However, its still not clear for me how to build a library will all dependencies using this PR.

**Comment by micronoz** [comment] 2021-08-31 19:52
When you install the library you can go into site-packages and edit the file directly. Since it's Python there is no 'building' of libraries when you run it.

**Comment by hrzn** [comment] 2021-09-04 14:16
This issue has now been fixed, and released in v0.11.0. You can upgrade Darts and it should work. Thanks for reporting!

**Closed by hrzn** 2021-09-04 14:16 UTC
Labels: bug, triage

**Comment by AdityaChaudhary** [comment] 2022-11-07 23:47
Hi @hrzn, I'm still facing this issue when using `TFTModel.load_from_checkpoint(MODEL_NAME)`.
`darts.__version__ = '0.22.0'`

### After executing `load_from_checkpoint` -

**model.trainer_params**
```
{'logger': <pytorch_lightning.loggers.tensorboard.TensorBoardLogger at 0x7fae701bf340>,
 'max_epochs': 25,
 'check_val_every_n_epoch': 1,
 'enable_checkpointing': True,
 'callbacks': [<pytorch_lightning.callbacks.model_checkpoint.ModelCheckpoint at 0x7fae701bf370>,
  <pytorch_lightning.callbacks.early_stopping.EarlyStopping at 0x7fae701bf400>],
 'enable_progress_bar': True,
 'accelerator': 'gpu',
 'devices': -1,
 'precision': 32}
```

**model.model.device**
`device(type='cpu')`


**Error: `Expected all tensors to be on the same device` after calling `fit`**
```
model.fit(
    series=target_train_l,
    past_covariates=past_cov_train_l,
    future_covariates=cov_train_l, 

    val_series=target_val_l,
    val_past_covariates=past_cov_val_l,
    val_future_covariates=cov_val_l,
    
    max_samples_per_ts = 1000,
    
    num_loader_workers=4,
    verbose=True)

```

No problems with the code otherwise. The model trains fine, predicts fine expect when its loaded from checkpoint.

**Comment by AdityaChaudhary** [comment] 2022-11-08 10:38
Same issue with `historical_forecasts` after loading a saved model from file `model = TFTModel.load(MODEL_FILE)`.
