### ISSUE TITLE
[BUG] Memory Issue while importing models from darts

### ISSUE THREAD

**Issue by aChatterjee13** [unit8co/darts#2226] opened 2024-02-13 13:26 UTC
Using darts v 0.23.1
Ananconda Python 3.8.x 
AMD 64

After I install the package and try to import any model I get the below error. Tried to replicate on a different computer and this did not occur. Any reason for this error and possible ways to fix the below?

Logs:

from darts.models import FFT
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
File "C:\Users\anindya\.conda envs\forecasting-prod\lib\site-packages\darts\models\init_.py", line 45, in <module> from darts.models.forecasting.lgbm import LightGBMModel File "C:\Users\anindya\.conda\envs\forecasting-prod\lib\site-packages\darts\models\forecasting\lgbm.py", line 15, in <module>
import lightgbm as 1gb
File "C:\Users\anindya\.conda\envs\forecasting-prod\lib\site-packages\lightgbm_init__.py", line 8, in <module> from basic import Booster, Dataset, Sequence, register_logger File "C:\Users\anindya\.conda\envs\forecasting-prod\lib\site-packages\lightgbm\basic.py", line 247, in <module>
LIB = _load_lib() File "C:
ars\anindya\.conda\envs\forecasting-prod\lib\site-packages\lightgbm\basic.py", line 232, in _load_lib
lib ctypes.cd11.LoadLibrary(lib_path[e])
File "C:\Users\anindya\.conda\envs\forecasting-prod\lib\ctypes_i.py", line 447, in LoadLibrary File "C:\Users\anindya\.conda\envs\forecasting-prod\lib\ctypes\init.py", line 369, in_init
return self. diltype(name)
self. handle = _dlopen(self._name, mode) OSError: [WinError 8] Not enough memory resources are available to process this command

**Comment by madtoinou** [comment] 2024-02-16 08:28
Hi @aChatterjee13,

It seems like the problem is coming from the lightgbm library. Please check if it's properly installed, or if this error is documented on their side.

If you don't need or use this model, you can uninstall it and Darts should still work fine as it's an optional dependency.

**Comment by madtoinou** [comment] 2024-04-17 07:10
This was fixed by #2304, it was caused by the order of the imports.

**Closed by madtoinou** 2024-04-17 07:10 UTC
Labels: bug, triage
