### ISSUE TITLE
[BUG] Loading a model from checkpoints, save it somewhere else and load it again, the model failed to make prediction.

### ISSUE THREAD

**Issue by ericlikp** [unit8co/darts#1568] opened 2023-02-15 09:07 UTC
**Describe the bug**
I fitted a model and then loaded the best checkpoint. I further saved this model somewhere else. This model failed to make predictions after it was loaded again.

**To Reproduce**
```
from darts.models.forecasting.block_rnn_model import BlockRNNModel
from darts.datasets import AirPassengersDataset

dataset = AirPassengersDataset().load()
train, test = dataset[:100], dataset[100-36:]
model = BlockRNNModel(
    input_chunk_length=36, 
    output_chunk_length=12, 
    model='LSTM', 
    hidden_dim=25, 
    n_rnn_layers=1, 
    hidden_fc_sizes=[20, 20], 
    dropout=0.0,
    batch_size=16,
    n_epochs=2,
    random_state=42,
    save_checkpoints=True,
    optimizer_kwargs={
        'lr': 4e-3
    },
    pl_trainer_kwargs= {
        "accelerator": "gpu",
        "devices": [0],
    }
)
model.fit(train, val_series=test, verbose=0)
best_model = model.load_from_checkpoint(model_name=model.model_name, best=True)
best_model.save('main_output/notebook/my_best_model.pt')
loaded_best_model = BlockRNNModel.load('main_output/notebook/my_best_model.pt')
output = loaded_best_model.predict(n=12).pd_dataframe()
print(output)
```

Output:
```
GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
HPU available: False, using: 0 HPUs
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]
`Trainer.fit` stopped: `max_epochs=2` reached.
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
/tmp/ipykernel_48998/2157301381.py in <module>
     25 best_model.save('main_output/notebook/my_best_model.pt')
     26 loaded_best_model = BlockRNNModel.load('main_output/notebook/my_best_model.pt')
---> 27 output = loaded_best_model.predict(n=12).pd_dataframe()
     28 print(output)

/opt/conda/lib/python3.8/site-packages/darts/utils/torch.py in decorator(self, *args, **kwargs)
    110         with fork_rng():
    111             manual_seed(self._random_instance.randint(0, high=MAX_TORCH_SEED_VALUE))
--> 112             return decorated(self, *args, **kwargs)
    113 
    114     return decorator

/opt/conda/lib/python3.8/site-packages/darts/models/forecasting/torch_forecasting_model.py in predict(self, n, series, past_covariates, future_covariates, trainer, batch_size, verbose, n_jobs, roll_size, num_samples, num_loader_workers, mc_dropout)
   1070         )
   1071 
-> 1072         predictions = self.predict_from_dataset(
   1073             n,
   1074             dataset,

/opt/conda/lib/python3.8/site-packages/darts/utils/torch.py in decorator(self, *args, **kwargs)
    110         with fork_rng():
    111             manual_seed(self._random_instance.randint(0, high=MAX_TORCH_SEED_VALUE))
--> 112             return decorated(self, *args, **kwargs)
    113 
    114     return decorator

/opt/conda/lib/python3.8/site-packages/darts/models/forecasting/torch_forecasting_model.py in predict_from_dataset(self, n, input_series_dataset, trainer, batch_size, verbose, n_jobs, roll_size, num_samples, num_loader_workers, mc_dropout)
   1174 
   1175         # set prediction parameters
-> 1176         self.model.set_predict_parameters(
   1177             n=n,
   1178             num_samples=num_samples,

AttributeError: 'NoneType' object has no attribute 'set_predict_parameters'
```

**System (please complete the following information):**
 - Python version: [e.g. 3.8.12]
 - darts version [e.g. 0.23.1]

**Additional context**
This code can be run on darts 0.22.0 successfully

**Comment by madtoinou** [comment] 2023-02-15 16:57
Hi,

This is a duplicate of #1561 where a fix is being discussed.

A simple workaround at the moment is to use `load_from_checkpoint` directly (on `loaded_best_model` in your example) instead of calling `save()` on a model that was not retrained.

**Closed by madtoinou** 2023-02-15 16:57 UTC
Labels: bug, triage
