### ISSUE TITLE
How the multi-step forecast work in the XGBoost implementation in Darts?

### ISSUE THREAD

**Issue by JKDomoguen** [unit8co/darts#1742] opened 2023-05-02 02:37 UTC
How do you implement multi output forecast for XGBoost as the native implementation of XGBoost does not implement multi-output forecast.
Do you use a wrapper like the one implemented here: https://towardsdatascience.com/multi-step-time-series-forecasting-with-xgboost-65d6820bec39#:~:text=XGBoost%20%5B1%5D%20is%20a%20fast,domains%20including%20time%20series%20forecasting. 

So essentially, 

One model predicting the 1st month in the future.
Another model predicting the 2nd month in the future.
The other model predicting the 3rd month in the future.

Training sets are different for 3 models. Targets are shifted by 1/2/3 months.

**Comment by JanFidor** [comment] 2023-05-02 10:48
Hi @JKDomoguen ! I'm not 100% certain if that's what you're looking for, but XGBoost has a parameter `multi_models` ([docs](https://unit8co.github.io/darts/generated_api/darts.models.forecasting.xgboost.html)) which if True creates a separate model for predicting each future lag

**Comment by vedantmehta08** [comment] 2023-05-02 22:23
Any ideas on how I can achieve the same (multi-step forecasting) behavior with features containing rolling mean of the target variable?

**Comment by madtoinou** [comment] 2023-05-03 06:44
Hi @vedantmehta08, I am not sure to understand your use case: you are trying to forecast several values at once (`output_chunk_length > 1`) and the input of the model is a single value, the rolling mean of the target variable?

To do so, you would have to use a `"transformer"` encoder ([doc](https://unit8co.github.io/darts/quickstart/00-quickstart.html#Encoders:-using-covariates-for-free)) to compute the rolling mean and use it as a covariate. Unless the rolling mean is absolutely necessary, you could just use `lags>1` (for regression models) or a `output_chunk_length > 1` (torch based models) to pass several input values to the model and have it predict several value at once.

**Comment by vedantmehta08** [comment] 2023-05-03 22:17
Thanks for your reply @madtoinou. output_chunk_length = 1 for my model. the input of the model is rolling mean of last 3 months of the target variable. How do I make sure that after forecasting the target variable at time step t+1, the rolling mean is calculated at t+1 and available to the model as an input while forecasting at time step t+2?

**Comment by madtoinou** [comment] 2023-06-14 06:42
Darts models do not support transformation on the target at the moment (tracked by #1515) but in the meantime, you could use a loop to apply the rolling mean manually:

```python
# number of values to predict with auto-regression
forecast_horizon=10
# original values, without the rolling mean
raw_values = ts.values()
# pre-allocate the time index
extended_time_index = pd.date_range(start=ts.start_time(), periods=len(ts)+forecast_horizon, freq=ts.freq)
# rolling mean applied
new_values = np.convolve(raw_values.flatten(), np.ones(3), 'valid')
training_ts=TimeSeries.from_times_and_values(times=extended_time_index[:len(new_values)],
                                             values=new_values)

# forecast_horizon is the number of values to predict
for i in range(forecast_horizon):
    prediction = model.predict(n=1, series=training_ts)
    # stack the values vertically
    raw_values = np.vstack([raw_values, prediction.values()])
    # apply the rolling mean on the array
    new_values = np.convolve(raw_values.flatten(), np.ones(3), 'valid')
    # create the new ts
    training_ts=TimeSeries.from_times_and_values(times=extended_time_index[:len(new_values)],
                                                 values=new_values)
```

We are forced to create a new `TimeSeries` at each iteration since they are immutable, which will slow down the code a little bit.

**Comment by vedantmehta08** [comment] 2023-06-14 19:47
Thanks for your reply. This solution definitely works, but won't be very optimal for my particular use case as my forecast horizon is quite long (90 time steps), plus my actual timeseries is generated from a grouped dataframe (to add static covariates) so making it a bit more complex challenge (atleast for me). But I appreciate you taking the time to reply to my questions :)

**Comment by madtoinou** [comment] 2023-06-15 08:01
No problem, since this feature (applying transformer to target during inference/training) is already tracked in the issue mentioned in my previous message, I am going to close this one as the initial question was already answered.

PS: You can add static_covariate to a ts by using `ts = ts.with_static_covariates(...)`

**Closed by madtoinou** 2023-06-15 08:01 UTC
Labels: question
