### ISSUE TITLE
[BUG] Breaking changes from scikit-learn 1.4.0

### ISSUE THREAD

**Issue by k-papadakis** [unit8co/darts#2180] opened 2024-01-21 17:17 UTC
**Describe the bug**
The private function `sklearn.utils.validation._check_fit_params` has been removed in scikit-learn version `1.4.0`. Installing darts with pip or conda automatically installs scikit-learn 1.4.0 and tries to import the removed function in places like `darts.utils.multioutput`, making the installation broken (e.g. can't import `NBEATS`).

**To Reproduce**
Install full darts with conda, using python=3.10, then try `from darts.models import NBEATSModel`

**Expected behavior**
`ImportError: cannot import name '_check_fit_params' from 'sklearn.utils.validation'`

**System (please complete the following information):**
 - Python version: 3.10
 - darts version 0.27.1 (latest in conda-forge)

**Comment by Escalion** [comment] 2024-01-21 20:24
I confirm this issue. Manually downgrading scikit-learn to 1.3.2 with `conda install scikit-learn==1.3.2` resolves the issue as a temporary fix.

**Comment by dennisbader** [comment] 2024-01-22 07:06
Hi, we have already fixed this and released darts version 0.27.2 a few hours ago (both pypi and conda packages). 

Could you try installing it again?

**Comment by dennisbader** [comment] 2024-01-22 11:22
It's not part of a nightly or release cycle, just a patch release.

We did catch this already a couple of days ago through our PR/merge workflows.
We decided to do a patch release, since also pandas and pytorch-lightning introduced some breaking changes in their newest versions.

You can track the changes in our CHANGELOG.md, however these dependency compatibility fixes (non-user facing) are not listet there.

**Comment by rehanguha** [comment] 2024-01-23 16:35
> It's not part of a nightly or release cycle, just a patch release.
> 
> We did catch this already a couple of days ago through our PR/merge workflows. We decided to do a patch release, since also pandas and pytorch-lightning introduced some breaking changes in their newest versions.
> 
> You can track the changes in our CHANGELOG.md, however these dependency compatibility fixes (non-user facing) are not listet there.

Makes sense. I would love to suggest to include all the PRs merged for the current release. I guess I will help all to tract all the changes.
But thanks a lot. :+1:

**Comment by connesy** [comment] 2024-01-26 11:35
@dennisbader I can confirm that installing `darts==0.27.2` and `scikit-learn==1.4.0` I am able to run `from darts.utils import multioutput` and `from darts.models import NBEATSModel` without issues.

**Closed** 2024-01-29 15:46 UTC
Labels: bug
