### ISSUE TITLE
[BUG] Residuals Function - LightGBMModel with lags>1

### ISSUE THREAD

**Issue by tbellamey** [unit8co/darts#1083] opened 2022-07-17 16:35 UTC
**Describe the bug**
When calling the residuals() function for a LightGBMModel with lags>1, I'm receiving the following ValueError:

File ~\site-packages\sklearn\utils\validation.py:805, in check_array(array, accept_sparse, accept_large_sparse, dtype, order, copy, force_all_finite, ensure_2d, allow_nd, ensure_min_samples, ensure_min_features, estimator)
    803     n_samples = _num_samples(array)
    804     if n_samples < ensure_min_samples:
--> 805         raise ValueError(
    806             "Found array with %d sample(s) (shape=%s) while a"
    807             " minimum of %d is required%s."
    808             % (n_samples, array.shape, ensure_min_samples, context)
    809         )
    811 if ensure_min_features > 0 and array.ndim == 2:
    812     n_features = array.shape[1]

**ValueError: Found array with 1 sample(s) (shape=(1, 84)) while a minimum of 2 is required.**

**To Reproduce**
fcst_hrzn = 84 [this parameter breaks the residuals() function call for LightGBMModel for any integer > 1]
model_LinReg = LinearRegressionModel(lags=fcst_hrzn, output_chunk_length=fcst_hrzn)
model_LightGBM = LightGBMModel(lags=fcst_hrzn, output_chunk_length=fcst_hrzn)

ts_LinReg_residuals = model_LinReg.residuals(series=ts_univariate,
                       forecast_horizon=fcst_hrzn,
                       verbose=True
                      )

ts_LightGBM_residuals = model_LightGBM.residuals(series=ts_LinReg_residuals,
                       forecast_horizon=fcst_hrzn,
                       verbose=True
                      )

**Expected behavior**
When running the code snippet above, the residuals() call on LinearRegressionModel works as expected. I can see the 'verbose' progress bar moving to completion. Then I can confirm the results look reasonable by calling plot_residuals_analysis()

plot_residuals_analysis(ts_LinReg_residuals,num_bins=50)

Ideally, the LightGBMModel residuals() function would complete the same calls without the ValueError thrown above

**System (please complete the following information):**
 - Python version: **3.9.7**
 - darts version **0.20.0**

**Additional context**
I have experimented with different integer values for the lags & output_chunk_length parameters. Only in the case of lags=1 & output_chunk_length=1 does the residuals() call work as expected for LightGBMModel. Otherwise the ValueError above is thrown. This is in contrast to the residuals() call for the LinearRegressionModel, which works as expected.

I have been able to call fit(), predict(), and backtest() functions successfully for the LightGBMModel on the same TimeSeries object, which is univariate, DatetimeIndex, and contains thousands of rows. So far only the residuals() function breaks with this ValueError.

**Comment by hrzn** [comment] 2023-01-05 15:01
@tbellamey could you indicate whether this issue is still present in recent versions of Darts?

**Comment by madtoinou** [comment] 2023-08-07 09:29
Hi @tbellamey,

It is intended that the `LightGBM` models compute the residuals on the residuals of the `LinearRegressionModel` and not on the original series? By definition, the residuals will be shorter than the original series : at least `input_chunk_length + output_chunk_length` values must be put aside to train the model and an additional `output_chunk_length` will be missing at the end (since no ground truth will be available). This could be the source of the error.

By taking this aspect into consideration, your code snippet works with darts 0.25.0:

```python
from darts.models import LinearRegressionModel, LightGBMModel
import darts.utils.timeseries_generation as tg

fcst_hrzn = 84
series = tg.linear_timeseries(length=588)

model_LinReg = LinearRegressionModel(lags=fcst_hrzn, output_chunk_length=fcst_hrzn)
model_LightGBM = LightGBMModel(lags=fcst_hrzn, output_chunk_length=fcst_hrzn)

# length = 336
ts_LinReg_residuals = model_LinReg.residuals(series=series,
forecast_horizon=fcst_hrzn,
verbose=True
)
# length = 85
ts_LightGBM_residuals = model_LightGBM.residuals(series=ts_LinReg_residuals,
forecast_horizon=fcst_hrzn,
verbose=True
)
```

Closing this for now, feel free to reopen if the problem still occurs or if something is unclear.

**Closed by madtoinou** 2023-08-07 09:29 UTC
Labels: bug, triage
