### ISSUE TITLE
[BUG] Issue on Pytorch Lightning - lightning evironment

### ISSUE THREAD

**Issue by johnnyb1509** [unit8co/darts#1563] opened 2023-02-12 15:59 UTC
**Describe the bug**
The bug occurs when I try to call a saved NBEATS Model, specifically:
- I have trained the NBEATS Model then save it using ```model.save()``` to produce a ```.pt``` file
- Try to call it during inference process but this error occur
```
...
-> 1579         __import__(module, level=0)
   1580         if self.proto >= 4:
   1581             return _getattribute(sys.modules[module], name)[0]

ModuleNotFoundError: No module named 'pytorch_lightning.plugins.environments.lightning_environment'
```

**To Reproduce**
Steps to reproduce the behavior: As I do above.

**Expected behavior**
Expect it can load the model normally

**System (please complete the following information):**
 - Python version: 3.9.16
 - darts version 0.23.0 (and also try 0.23.1)
 - pytorch-lightning: 1.8.6
 - pytorch: 1.13.1-cpuonly (as my laptop does not have GPU)
 - OS: wsl Ubuntu

**Comment by madtoinou** [comment] 2023-02-13 17:47
Hi,

I could not reproduce the bug using the following snippet:

```python
series = TimeSeries.from_series(pd.Series(np.random.random(100)), freq="1H")

model = NBEATSModel(
    4,
    4,
    save_checkpoints=False,
    force_reset=True,
)
model.fit(series, verbose=False, epochs=5)

fname = "my_model.pt"
model.save(fname)

m_load = NBEATSModel.load(fname)
m_load.predict(2)
```

My environment is pretty much identical to yours:
- Python version: 3.9.15
- darts version 0.23.1
- pytorch-lightning: 1.8.6
- torch: 1.13.1
- OS: Mac

I suppose that something broke in the install, may I suggest you to create a new python environment and to reinstall darts?

**Comment by hrzn** [comment] 2023-02-22 19:21
Closing for now.

**Closed by hrzn** 2023-02-22 19:21 UTC
Labels: bug, triage
