### ISSUE TITLE
How can I add the EarlyStopping with validation-related losses when running historical_forecasts with retrain=True?

### ISSUE THREAD

**Issue by buihaduong** [unit8co/darts#1876] opened 2023-07-03 03:33 UTC
Hi,

How can I add the EarlyStopping with validation-related losses when running historical_forecasts with retrain=True?

For example:

```python
my_stopper = EarlyStopping(
    monitor="val_MeanAbsolutePercentageError", 
    patience=5,
    min_delta=0.05,
    mode='min',
)
pl_trainer_kwargs = {
    "accelerator": "gpu",
    "callbacks": [my_stopper],
    "logger": [neptune_logger]
    }

model_tft = TFTModel(input_chunk_length=360,
    output_chunk_length=horizon,
    batch_size=64,
    n_epochs=64,
    nr_epochs_val_period=1,
    random_state=42,
    save_checkpoints=True,
    force_reset=True,
    optimizer_kwargs={'lr': lr_finder.suggestion()},
    torch_metrics=MetricCollection([MeanAbsolutePercentageError(), MeanSquaredError()]),
    add_encoders={
        'cyclic': {'future': ['month', 'dayofweek'],
                   'past': ['month', 'dayofweek'],
                },
        'transformer': Scaler()
    },
    add_relative_index=True,
    pl_trainer_kwargs = pl_trainer_kwargs
)

model_tft .historical_forecasts(
        series=series_scaled,
        past_covariates=past_covariates_scaled,
        start=split_point,
        forecast_horizon=horizon,
        stride=horizon,
        retrain=True,
        last_points_only=False,
        verbose=True
    )
``` 

Thank you :)

**Comment by dennisbader** [comment] 2023-07-03 08:20
Hi @buihaduong. Unfortunately, this is currently not possible. Let me add it to our backlog.

**Comment by dennisbader** [comment] 2023-07-03 11:02
Closing this as duplicate of #645.

**Closed by dennisbader** 2023-07-03 11:02 UTC
