### ISSUE TITLE
Adding LightGBM

### ISSUE THREAD

**Issue by whiletruelearn** [unit8co/darts#293] opened 2021-03-12 09:52 UTC
**Is your feature request related to a current problem? Please describe.**
LightGBM won the M5 time series forecasting competition. It will be a good algorithm to add.
https://www.innovating-automation.blog/m5-forecasting-competition/

**Describe proposed solution**
Create a wrapper for the lightgbm library in `darts`

**Comment by tneuer** [comment] 2021-03-12 10:52
There are a lot of great algorithms out there we're still planning to implement in future releases, but you're completely right. LightGBM should definitely be high up on our priority list. Thanks for bringing this to our attention!

**Comment by RNogales94** [comment] 2021-04-19 19:03
I have code this feature, but when I try to use lightGBM for a simple example (Airline passenger forecast) the LightGBM predict a constant, because the model becomes too simple. 

I can share the code with a pull request but I think there's something wrong. I can show you what I have done by google meet or something before the PR if you wish

**Comment by tneuer** [comment] 2021-04-20 08:00
Hey @RNogales94, thanks for bringing up the issue again. We have also been working on this problem and a few general notes to update all interested folk:

- You are right that Tree-Based-Models tend to predict the mean (that's the operation performed on the leaf-level) and sometimes have troubles with time series, **especially** when you deal with a time series with non-zero trend (like the passenger data set). The user should perform differencing before passing any TimeSeries to a Tree-Based-Model (this feature has just be enabled in Darts by calling `.diff()` on any `TimeSeries`.)
- For now, we decided not to implement the LightGBM class from the `lightgbm` library, because it requires additional dependencies outside of python which cannot be downloaded via conda. On a Mac you need to perform [these](https://lightgbm.readthedocs.io/en/latest/Installation-Guide.html#macos) steps to make `lightgbm` work and we already have so many Python dependencies that we decided against having even more out-of-Python dependencies which would break the `Darts` installation.
- In the near future we release models wrapping around Random Forest and  HistGradientBoostingRegressor from scikit-learn (it is currently in the PR and we need to review it properly).
- In the same release we enable the user to use Darts for every model exposing the .fit() and .predict() methods (so every scikit-learn model). You then could download LightGBM separately and then pass that model directly to the base class called (for now) `RegressionModel` to make everything work.

@RNogales94 I would still be eager to see how you implemented the model. Maybe we see something that would improve on our implementation. As it is still in the PR we could change and improve it without causing any problems. 
Would you mind making a PR for your implementation. It will probably not be accepted due to the mentioned concerns with `lightgbm` but I think that would still be the easiest way to review the code together.

**Comment by RNogales94** [comment] 2021-04-20 08:05
> For now, we decided not to implement the LightGBM class from the lightgbm library, because it requires additional dependencies outside of python which cannot be downloaded via conda.

I know, I have added it to the setup.py in order to make the installation modular, so you don't download it if you are not interested, I've follow your fb prophet approach

I do the PR :)

**Comment by hrzn** [comment] 2021-05-24 13:39
We have released the changes explained by @tneuer above in version 0.8.0. So now you can
* Wrap around any scikit-learn model
* Wrap around a LightGBM model (offering `fit()` and `predict()` interface) if you install LightGBM yourself on your environement.

I'll thus close the issue, but we would be happy to learn about your experiences using these models!

**Closed by hrzn** 2021-05-24 13:39 UTC
Labels: feature request, triage
