### ISSUE TITLE
[BUG] N_Beats in probabilistic mode requires a scaler

### ISSUE THREAD

**Issue by mrtn37** [unit8co/darts#1788] opened 2023-05-19 09:28 UTC
The N_Beats model in the probabilistic mode requires the usage of a Scaler beforehand.
Otherwise the results are unplausible when comparing them to the deterministic version.

Since this is not explicitely mentioned in the docs, I believe this behavior to be unintended.

**To Reproduce**
Use a simple N_Beats model _without_ any Scaler beforehand.
NBEATSModel(
    input_chunk_length=30,
    output_chunk_length=10,
    generic_architecture=False,
    num_blocks=3,
    num_layers=4,
    layer_widths=512,
    batch_size=32,
    model_name="nbeats_det",
    #likelihood=GaussianLikelihood(),
    force_reset=True,
    random_state=42
)
Depending on wether the likelihood paramter is defined, the results from the deterministic and the probabilistic version (taking the mean oder the median) are numerically _not_ of the same magnitude. 
They seem to be comparable, as soon as a scaler is used beforehand.

**Expected behavior**
I expect the results of the deterministic version to be somewhat similar to those of the probabilistic version. 

**System (please complete the following information):**
 - Python version: 3.8.16
 - darts version 0.23.1

**Comment by mrtn37** [comment] 2023-05-31 07:18
Thank you for your explanation and for the great example. I was not aware that you could tune the model that way and make the gaussian forecast work that way. I will have to read up, what it exactly does :)

I agree on the logical matter, that scaling is often sensible and should be done in most cases.

My point if a more formal or technical one. If the need of a scaler is not a hard requirement, the code should run without any errors if no scaling was done. Hence I regard this behavior as bug.
Judging by my 'naive' approach,as a user of this library, I did not expect that behavior.
Maybe the model could test whether the data is scaled and, if not, throw a warning?

**Comment by alexcolpitts96** [comment] 2023-05-31 07:50
I think that the idea of darts having models check for data quality goes against the role that darts aims to fit as a tool. This is more of a design philosophy problem. I am not a core developer for darts, but have been using it for academic and professional purposes.

Darts allows for a lot of the tedious boilerplate code associated with timeseries applications to be abstracted. Writing your own scalers, dataloaders, model saving and loading, etc can be pretty tedious. Vanilla torch takes a decent amount of work to go from an idea to a deployable model. Pytorch Lightning helps remove training boilerplate; however, there is still a ton of tooling that darts adds around it. Not only does darts do that with torch-based models, but it also glues together a bunch of other popular timeseries libraries. 

The core devs may think differently, but I am not sure a scale-check like you propose would be in-scope for darts. There are many ways that scaling (or lack of) can be compensated for, so a warning wouldn't be meaningful. That being said, adding quality checks and modeling your data before feeding it into darts (or other ML tools) will make your life a lot easier in the long-run.

**Comment by mrtn37** [comment] 2023-05-31 08:31
Okay, I am fine with that :)

Still, there is a technical feasible combination of parameter and model calls which leads to a 'bad' result.
I am not arguing the case, that a more experienced user would avoid that based on his/her knowledge.
However, from a coding perspective, such behavior should not be put to the user to resolve resp. to interpret without any further hints on what is going on. If the code accepts such parameter setting, the results should be within the user's expectation. As a naive example: I put in values in the range of ~100, I expect an output in that order and not in the order of ~0.1.
As you put it: This is more of a design philosophy problem 😊

Thank you for your replies, I learned a lot 😊

**Comment by madtoinou** [comment] 2024-08-27 16:20
@alexcolpitts96

Thanks a lot for taking the time to answer this issue and to include this nice code snippet.

@mrtn37

As explained in the thread, scaling the features prior to training a deep-learning model is a good practice that we encourage all the users of the library to use. As for the design philosophy, Darts aims at giving as much control as possible to the user without having warning messages appearing all the time to give recommendations/advises :) But thank you for opening this issue, I am sure a lot of others learnt from it!

I am closing this (way behind schedule) since this is not a bug per se, and wishing you good luck with future "model under-performance investigation" ;)

**Closed by madtoinou** 2024-08-27 16:20 UTC
Labels: question
