### ISSUE TITLE
Support for zero-shot forecasting using LLM

### ISSUE THREAD

**Issue by kyleke1998** [unit8co/darts#2093] opened 2023-11-26 03:03 UTC
A recent paper titled "Large Language Models Are Zero-Shot Time Series Forecasters" [https://arxiv.org/abs/2310.07820](url) 
showed that LLMs have on par if not better forecasting performance compared to  SOTA models while performing zero-shot inference. The key is really some simple pre-processing and post processing. It would be cool if DARTs enabled a feature to allow plugging in a LLM for zero-shot forecasting.

**Comment by madtoinou** [comment] 2023-11-27 09:05
Related to #1715.

WDYT @dennisbader ?

**Comment by dennisbader** [comment] 2023-11-27 09:37
Hi @kyleke1998. Indeed related to #1715. I still believe there are other areas which have higher priority to improve first.
We are definitely not against it, but this is something where we'd need more capacity/help from the community.

**Comment by madtoinou** [comment] 2024-07-05 08:10
To centralize conversation in a single issue, closing this one, duplicate of  #2359.

As mentioned by Dennis, we would prefer to focus our capacity on other features but PRs from the Darts community are welcomed :) And before implementing it, agreeing on a nice architecture would be probably necessary.

**Closed by madtoinou** 2024-07-05 08:10 UTC
Labels: feature request
