### ISSUE TITLE
Sagemaker Issue: Failure when combining Darts with 'import sagemaker' inside of AWS Sagemaker notebook.

### ISSUE THREAD

**Issue by fjehlik-ventera** [unit8co/darts#1898] opened 2023-07-13 17:14 UTC
**Describe the bug**
After creating an AWS Sagemaker Notebook and selecting an environment (i.e. Image = DataScience, Kernel = Python3), if you !pip install darts and then try to import sagemaker after installing/importing darts, the following error occurs:

TypeError: Descriptors cannot not be created directly.
If this call came from a _pb2.py file, your generated code is out of date and must be regenerated with protoc >= 3.19.0.
If you cannot immediately regenerate your protos, some other possible workarounds are:
 1. Downgrade the protobuf package to 3.20.x or lower.
 2. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use pure-Python parsing and will be much slower).

More information: https://developers.google.com/protocol-buffers/docs/news/2022-05-06#python-updates

**To Reproduce**
Launch AWS Sagemaker, create a new notebook with an environment of your choice, and try the following one cell of code: 

!pip install darts
import sagemaker

Also, I tried setting up a conda environment via the command line and that also fails The following should freeze while generating a new environment:

conda create -n darts python==3.9 pip
conda install -c conda-forge darts
conda install -c conda-forge sagemaker 

(the following freezes with compatibility issues). 

**Expected behavior**
No error with regards to protobuf package. 

**System (please complete the following information):**
 - Python version: 3.9
 - darts version: 0.24.0
 - sagemaker version: 2.171.0 

**Additional context**
I tried downgrading protobuf, changing environments (i.e. Image = PyTorch 1.10, Kernel = Python3), etc., but can not get darts to run in sagemaker if one needs to import sagemaker (a requirement for my projects). Importing other AWS libraries (i.e. boto3) is no issue.  

**ps.**
Your library is AWESOME, major high-five~

**Comment by madtoinou** [comment] 2023-07-14 06:23
Hi @fjehlik-ventera,

Thank you for reporting this bug. I think that this is a duplicate of  #1882 and should be solved with the next release (by the end of July if everything goes according to planning).

Keeping this open so that we don't forget to test this after the release.

**Comment by fjehlik-ventera** [comment] 2023-07-14 10:46
Thank you folks, I appreciate the prompt attention to this. I will stay tuned and am looking forward to the new release~

**Comment by madtoinou** [comment] 2023-08-07 14:37
Hi @fjehlik-ventera,

darts 0.25.0 was released today and should solve the issue. I am going to close the issue but please reopen it if the problem persists 😄

**Closed by madtoinou** 2023-08-07 14:37 UTC
Labels: bug
