### ISSUE TITLE
[BUG] darts_logs directory missing when loading a model in a different directory then one created in 

### ISSUE THREAD

**Issue by matanost-netop** [unit8co/darts#925] opened 2022-04-20 13:57 UTC
I work by saving models in training and loading them in inference.

First I create a model 'model' with log_tensorboard=True, an object from a sub-class of TorchForecastingModel. Let's say TCNModel.
The model.model.trainer object expects to log activity into ./darts_logs directory.
Then I save the model using model.save_model(path), and load it using TCNModel.load_model(path) In a different directory then the one created in.
Upon loading, the darts_logs directory doesn't exist and the model raises an exception upon predicting saying that the directory doesn't exist or there are no writing permissions to it.

To my understanding the source of the bug is: 
the directory is created using TorchForecastingModel._create_save_dirs(), which is only called on model creation and not when loading.

A solution to the bug would be to either disable this particular loading automatically or creating darts_logs in the new directory.

I avoid the failure by manually setting the following after the loading is done:
    model.model.trainer.logger = None

I will also train the model using log_tensorboard=False from now on, but I still consider this behavior buggy.

Darts version darts==0.19.0
pip 22.0.4 (python 3.9)

**Comment by dennisbader** [comment] 2022-04-24 15:46
Hi @matanost-netop and thanks for reporting. What you're saying is right, if you use TensorBoard logging and manually save/load the model to/from a different directory, the trainer can‘t find the logging files anymore.

For now you could just pass a new trainer object to predict() which should prevent this problem:
```
import pytorch_lightning as pl

# logic for loading without logger
model_loaded = TCNModel.load_model("mymodel.pth.tar")

# get the original PyTorch Lightning Trainer parameters and deactivate logging
trainer_params = model_loaded.trainer_params
trainer_params.update({
    "logger": False,
    "enable_model_summary": False
})

# predict with the new trainer object. This will automatically update the internal TCNModel trainer so you 
# don't have to repeat it for every `predict()` call
preds = model_loaded.predict(..., trainer=pl.Trainer(**trainer_params))
```

I'll add this to our backlog.

**Comment by dennisbader** [comment] 2022-04-25 18:30
I thought that we fixed this issue in darts version 0.19.0. 

Could it be that you are saving in a different environment than you are loading the model?

**Comment by matanost-netop** [comment] 2022-04-25 18:41
Yes. Both have GPUs, but not the same GPU.
They have different specs since training requires more resources than inference.

**Comment by dennisbader** [comment] 2022-04-25 20:21
Can you ensure that in both environments you have darts version 0.19.0?

**Comment by matanost-netop** [comment] 2022-04-26 09:06
Yes. Both have 0.19.0.

**Comment by dennisbader** [comment] 2022-05-01 11:34
I cannot reproduce this issue as I don't have the hardware for it.

With our API we try to simplify model usage for the typical use cases (training/saving/loading/predicting on the same CPU/GPU). For more advanced use cases (such as yours) we already provide the option to give a custom trainer to `predict()`.

**Comment by ludomitch** [comment] 2022-05-30 19:26
Hello, I've encountered the same problem. I am trying to load a model and run a prediction, but I keep encountering this problem
`Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/ludo/Desktop//ml_ops/optimise_predict.py", line 81, in <module>
    ) = opt.predict()
  File "/Users/ludo/Desktop//ml_ops/ml_models/optimise/optimise.py", line 112, in predict
    predictions, full_ensemble_predictions = m.predict(
  File "/Users/ludo/Desktop//ml_ops/ml_models/forecast/darts_model.py", line 174, in predict
    predictions = self.model.predict(
  File "/Users/ludo/Desktop//ml_ops/venv/lib/python3.8/site-packages/darts/models/forecasting/tft_model.py", line 945, in predict
    return super().predict(n, *args, **kwargs)
  File "/Users/ludo/Desktop//ml_ops/venv/lib/python3.8/site-packages/darts/utils/torch.py", line 70, in decorator
    return decorated(self, *args, **kwargs)
  File "/Users/ludo/Desktop//ml_ops/venv/lib/python3.8/site-packages/darts/models/forecasting/torch_forecasting_model.py", line 1100, in predict
    predictions = self.predict_from_dataset(
  File "/Users/ludo/Desktop//ml_ops/venv/lib/python3.8/site-packages/darts/utils/torch.py", line 70, in decorator
    return decorated(self, *args, **kwargs)
  File "/Users/ludo/Desktop//ml_ops/venv/lib/python3.8/site-packages/darts/models/forecasting/torch_forecasting_model.py", line 1236, in predict_from_dataset
    predictions = self.trainer.predict(self.model, pred_loader)
  File "/Users/ludo/Desktop//ml_ops/venv/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1022, in predict
    self.strategy.model = model or self.lightning_module
  File "/Users/ludo/Desktop//ml_ops/venv/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 2007, in strategy
    return self._accelerator_connector.strategy
AttributeError: 'Trainer' object has no attribute '_accelerator_connector'`


It seems to be linked to the issue above. @matanost-netop When you say that you solved it by loading a new trainer instance, how did you do this exactly? Really struggling. Any help would be much appreciated. 

Using u8darts==0.19.0.

I would attach a code snippet, but we're using a lot of custom logic so wouldn't be very useful.

**Comment by matanost-netop** [comment] 2022-06-01 23:43
Hi @ludomitch, 

As you can see in 
[https://github.com/unit8co/darts/blob/9e1b565e12412240dafe9af3093fd38982089246/darts/models/forecasting/torch_forecasting_model.py#L1362](url)
the model has a PyTorch Lightning Trainer object which is loaded together with the model itself.
What I did is creating a new Trainer object, to replace the loaded one which IMHO shown some issues coming from differences between the saving environment and loading one.

I added this code after loading model into 'model' using TCNModel.load_model(). 
In my case model is a TCNModel object.

```
trainer_params = model.trainer_params
trainer_params.update({
    'logger': False,
    'enable_model_summary': False,
    'enable_progress_bar': False
})
trainer_params['callbacks'] = [
    c for c in trainer_params['callbacks'] if 
                               ('TQDMProgressBar' not in str(c.__class__))
]

model.trainer = pl.Trainer(**trainer_params)
model.model.trainer = model.trainer
```

It is very possible that your issue will be solve simply by doing the following, but I provided the code above since I don't remember exactly why I added everything.

```
model.trainer = pl.Trainer(**model.trainer_params)
model.model.trainer = model.trainer
```

**Comment by hrzn** [comment] 2023-01-05 13:47
@dennisbader could we close this one?

**Closed** 2023-03-08 08:57 UTC
Labels: bug
