### ISSUE TITLE
[BUG] Multiple timeseries training failing for linear regression due to float overflow 

### ISSUE THREAD

**Issue by albin02t** [unit8co/darts#1550] opened 2023-02-09 11:19 UTC
**Describe the bug**
I have fitted the linear regression model for a multiple timeseries problem for 5 timeseries series to forecast the target 'target_value' for each series.
This is what the dataset for the first series looks like:

![image](https://user-images.githubusercontent.com/69189799/218429242-9da27d76-ca6d-4615-a500-0e7fa5fbc990.png)

The 'target_value' ranges from 0 to 2155.
For one of the series when using the model for prediction for next 144 steps, it fails with the following message:

![image](https://user-images.githubusercontent.com/69189799/217796425-b933a658-f2e0-453b-85d4-a3a097d145b4.png)

After looking into the code, it seems like during model prediction, there is matrix multiplication being applied and due to which v large values are generated which exceed the limits of float 64 and generates inf value which then throws error during predicted values validation.

When replacing one of the values used in training for 'feature_1' which is 1906.992798 to a smaller value, the training works fine.

The predicted values are in the range 0f e250 when the max actual value is 2155. Why does the model behave as so?
Why do we apply matrix multiplication? and shouldn't we upcast the float values if there are larger values generated during prediction?

**To Reproduce**
Train Linear regression multiple timeseries model for covariates that have values greater than 1900 and with high decimal places. Use the model for prediction of one of the groups 

**System (please complete the following information):**
 - Python version: 3.7.15
 - darts version : 0.18.0

**Comment by dennisbader** [comment] 2023-02-10 09:38
Hi @albin02t . This seems strange to me.
Could you provide a minimum working example to reproduce this issue?

If your data is not publicly available, you can generate some dummy time series data either with
- `TimeSeries.from_times_and_values()` (see the docs here)
- or with our time series generation utils from [here](https://unit8co.github.io/darts/generated_api/darts.utils.timeseries_generation.html#darts.utils.timeseries_generation.linear_timeseries).

**Comment by madtoinou** [comment] 2023-08-16 11:08
Hi @albin02t,

The matrix multiplication is necessary to apply the linear regression weights to the data. Since darts rely on the sklearn implementation, we do not have control on the dtype of the arrays during the training/inference.

I am going to close this issue, feel free to reopen it with a reproducible example if the problem persists on the latest version of darts.

**Closed by madtoinou** 2023-08-16 11:08 UTC
Labels: bug, triage
