### ISSUE TITLE
[BUG] ValueError: high is out of bounds for int32

### ISSUE THREAD

**Issue by SharkFin-top** [unit8co/darts#289] opened 2021-03-10 06:36 UTC
When I run
from darts.models import TCNModel 
model = TCNModel(
    input_size=24,
    n_epochs=20, 
    input_length=365,
    output_length=7, 
    dropout=0, 
    dilation_base=2, 
    weight_norm=True,
    kernel_size=7,
    num_filters=4,
    random_state=0
)

the output is

ValueError                                Traceback (most recent call last)
<ipython-input-5-bd8b0190ff7e> in <module>
      1 from darts.models import TCNModel
----> 2 model = TCNModel(
      3     input_size=24,
      4     n_epochs=20,
      5     input_length=365,

D:\Anaconda3\lib\site-packages\darts\utils\torch.py in decorator(self, *args, **kwargs)
     62 
     63         with fork_rng():
---> 64             manual_seed(self._random_instance.randint(0, high=MAX_TORCH_SEED_VALUE))
     65             decorated(self, *args, **kwargs)
     66     return decorator

mtrand.pyx in numpy.random.mtrand.RandomState.randint()

_bounded_integers.pyx in numpy.random._bounded_integers._rand_int32()

ValueError: high is out of bounds for int32

I try many ways, but I do not know why.

Please, help me!

Thanks♪(･ω･)ﾉ

**System (please complete the following information):**
 - Python version: [e.g. 3.8.5]
 - darts version [e.g. 0.6.1]

**Comment by cosmerodolfo** [comment] 2021-03-11 12:53
Same error, but running NBEATSmodel.

**Comment by SharkFin-top** [comment] 2021-03-11 12:56
> Same error, but running NBEATSmodel.

Well, I try all other model in darts.  And I get the same error.
I don't know why. My Pytorch  may be wrong? 
o(╥﹏╥)o

**Comment by SharkFin-top** [comment] 2021-03-12 02:25
@cosmerodolfo 

I solve it !!!   Do like this
[https://stackoverflow.com/questions/66514169/when-tcn-is-used-for-prediction-python-there-is-a-valueerror-high-is-out-of-b](url)

Life is fucking amazing!!
ヾ(◍°∇°◍)ﾉﾞ ヾ(◍°∇°◍)ﾉﾞ

**Comment by cosmerodolfo** [comment] 2021-03-12 18:56
@SharkFin-top, thanks for your feedback!

Now it seems to be working properly.
Tks again!

**Comment by hrzn** [comment] 2021-03-17 13:47
Thanks for flagging, we'll correct it in an upcoming release.

**Comment by SharkFin-top** [comment] 2021-03-20 02:29
> Thanks for flagging, we'll correct it in an upcoming release.

Go ahead! 
I trust you guys!

**Comment by hrzn** [comment] 2021-04-08 13:16
Duplicate of https://github.com/unit8co/darts/issues/235

**Closed by hrzn** 2021-04-08 13:16 UTC
Labels: bug, duplicate
