### ISSUE TITLE
[BUG] Error installing dart from scratch in a brand new computer

### ISSUE THREAD

**Issue by jlropes** [unit8co/darts#1375] opened 2022-11-21 13:35 UTC
I have been using dart from few weeks without problems. Few days ago I changed my laptop and now I'm reinstalling all my modules. 
Unfortunately I'm not able to install it anymore because during the process there's the following error:

Collecting darts
  Using cached darts-0.22.0-py3-none-any.whl (451 kB)
  Using cached darts-0.21.0-py3-none-any.whl (424 kB)
  Using cached darts-0.20.0-py3-none-any.whl (400 kB)
Collecting holidays>=0.11.1
  Using cached holidays-0.17-py3-none-any.whl (187 kB)
Requirement already satisfied: ipython>=7.0.0 in c:\users\cordellina-g\appdata\local\programs\python\python311\lib\site-packages (from darts) (8.6.0)
Requirement already satisfied: joblib>=0.16.0 in c:\users\cordellina-g\appdata\local\programs\python\python311\lib\site-packages (from darts) (1.2.0)
Collecting lightgbm>=2.2.3
  Using cached lightgbm-3.3.3-py3-none-win_amd64.whl (1.0 MB)
Requirement already satisfied: matplotlib>=3.3.0 in c:\users\cordellina-g\appdata\local\programs\python\python311\lib\site-packages (from darts) (3.6.2)
Collecting nfoursid>=1.0.0
  Using cached nfoursid-1.0.1-py3-none-any.whl (16 kB)
Requirement already satisfied: numpy>=1.19.0 in c:\users\cordellina-g\appdata\local\programs\python\python311\lib\site-packages (from darts) (1.23.4)
Requirement already satisfied: pandas>=1.0.5 in c:\users\cordellina-g\appdata\local\programs\python\python311\lib\site-packages (from darts) (1.5.1)
Requirement already satisfied: requests>=2.22.0 in c:\users\cordellina-g\appdata\local\programs\python\python311\lib\site-packages (from darts) (2.28.1)
Requirement already satisfied: scikit-learn>=1.0.1 in c:\users\cordellina-g\appdata\local\programs\python\python311\lib\site-packages (from darts) (1.1.3)
Requirement already satisfied: scipy>=1.3.2 in c:\users\cordellina-g\appdata\local\programs\python\python311\lib\site-packages (from darts) (1.9.3)
Collecting statsforecast>=0.5.2
  Using cached statsforecast-1.3.1-py3-none-any.whl (86 kB)
Collecting statsmodels>=0.13.0
  Using cached statsmodels-0.13.5-cp311-cp311-win_amd64.whl (9.0 MB)
Collecting tqdm>=4.60.0
  Using cached tqdm-4.64.1-py2.py3-none-any.whl (78 kB)
Collecting xarray>=0.17.0
  Using cached xarray-2022.11.0-py3-none-any.whl (963 kB)
Collecting pmdarima>=1.8.0
  Using cached pmdarima-2.0.1.tar.gz (638 kB)
  Preparing metadata (setup.py) ... done
Collecting tbats>=1.1.0
  Using cached tbats-1.1.1-py3-none-any.whl (43 kB)
Collecting pytorch-lightning>=1.5.0
  Using cached pytorch_lightning-1.8.2-py3-none-any.whl (798 kB)
Collecting darts
  Using cached darts-0.19.0-py3-none-any.whl (370 kB)
  Using cached darts-0.18.0-py3-none-any.whl (359 kB)
  Using cached darts-0.17.1-py3-none-any.whl (346 kB)
  Using cached darts-0.17.0-py3-none-any.whl (343 kB)
  Using cached darts-0.16.1-py3-none-any.whl (326 kB)
  Using cached darts-0.16.0-py3-none-any.whl (326 kB)
  Using cached darts-0.15.0-py3-none-any.whl (322 kB)
Collecting filterpy>=1.4.5
  Using cached filterpy-1.4.5.zip (177 kB)
  Preparing metadata (setup.py) ... done
Collecting darts
  Using cached darts-0.14.0-py3-none-any.whl (290 kB)
  Using cached darts-0.13.1-py3-none-any.whl (286 kB)
  Using cached darts-0.13.0-py3-none-any.whl (285 kB)
  Using cached darts-0.12.0-py3-none-any.whl (253 kB)
Collecting pandas<1.3.0,>=1.2.0
  Using cached pandas-1.2.5.tar.gz (5.5 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting scikit-learn<1.0.0,>=0.24.0
  Using cached scikit-learn-0.24.2.tar.gz (7.5 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [26 lines of output]
      Partial import of sklearn during the build process.
      Traceback (most recent call last):
        File "C:\Users\cordellina-g\AppData\Local\Programs\Python\Python311\Lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 351, in <module>
          main()
        File "C:\Users\cordellina-g\AppData\Local\Programs\Python\Python311\Lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 333, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\cordellina-g\AppData\Local\Programs\Python\Python311\Lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 152, in prepare_metadata_for_build_wheel
          return hook(metadata_directory, config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\cordellina-g\AppData\Local\Temp\pip-build-env-g75z77ph\overlay\Lib\site-packages\setuptools\build_meta.py", line 377, in prepare_metadata_for_build_wheel
          self.run_setup()
        File "C:\Users\cordellina-g\AppData\Local\Temp\pip-build-env-g75z77ph\overlay\Lib\site-packages\setuptools\build_meta.py", line 484, in run_setup
          self).run_setup(setup_script=setup_script)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\cordellina-g\AppData\Local\Temp\pip-build-env-g75z77ph\overlay\Lib\site-packages\setuptools\build_meta.py", line 335, in run_setup
          exec(code, locals())
        File "<string>", line 301, in <module>
        File "<string>", line 293, in setup_package
        File "C:\Users\cordellina-g\AppData\Local\Temp\pip-build-env-g75z77ph\overlay\Lib\site-packages\numpy\distutils\__init__.py", line 26, in <module>
          from . import ccompiler
        File "C:\Users\cordellina-g\AppData\Local\Temp\pip-build-env-g75z77ph\overlay\Lib\site-packages\numpy\distutils\ccompiler.py", line 20, in <module>
          from numpy.distutils import log
        File "C:\Users\cordellina-g\AppData\Local\Temp\pip-build-env-g75z77ph\overlay\Lib\site-packages\numpy\distutils\log.py", line 4, in <module>
          from distutils.log import Log as old_Log
      ImportError: cannot import name 'Log' from 'distutils.log' (C:\Users\cordellina-g\AppData\Local\Temp\pip-build-env-g75z77ph\overlay\Lib\site-packages\setuptools\_distutils\log.py)
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

My python version is  3.11.0 and I'm installing darts via pip.

Thanks for any feedback.
Gianluca

**Comment by eliane-maalouf** [comment] 2022-11-21 22:08
Hello @jlropes , I think the problem is due to the version of python, for the moment Darts is not supported with Python 3.11 ; you can find all the version supported at the moment at https://pypi.org/project/darts/ under "programming languages". You can try to downgrade the version of python (or create a new env. with a lower version of python) and try installing Darts again and let us know if the issue persists.

**Comment by jlropes** [comment] 2022-11-23 09:00
Thanks for your feedback. Installing python 3.10 it works.

**Comment by eliane-maalouf** [comment] 2022-11-23 10:27
great, glad it worked. I will go on and close this issue.

**Closed by eliane-maalouf** 2022-11-23 10:27 UTC
Labels: bug, triage
