### ISSUE TITLE
[BUG] prediction after Multi GPU  training throws assertion error

### ISSUE THREAD

**Issue by Nishanth009** [unit8co/darts#1966] opened 2023-08-24 10:03 UTC
Hi,
I was trying to train a RNN model using multi gpu. I have followed instructions from website using as follows for enabling multi gpu
pl_trainer_kwargs = {"accelerator": "gpu", "devices": -1, "auto_select_gpus": True}

The training is successful but while predicting I am getting assertion error

/site-packages/pytorch_lightning/overrides/distributed.py", line 213, in __init__
    assert self.num_samples >= 1 or self.total_size == 0
   
Having this issue we are not able to Darts for multi gpu training please some one let me know what change is required to generate the predictions when multiple gpu is enabled. Thanks

**Comment by madtoinou** [comment] 2023-08-25 07:33
Hi @Nishanth009,

I think that this is a duplicate of #1945, but sadly, we don't have the hardware to reproduce it at the moment.

**Closed** 2024-03-05 13:11 UTC
Labels: bug, gpu
