### ISSUE TITLE
Train with GPU, save .pkl and then load and predict in CPU environment

### ISSUE THREAD

**Issue by adriengauche** [unit8co/darts#1640] opened 2023-03-10 13:07 UTC
**Is your feature request related to a current problem? Please describe.**
Today, it is not possible to train a model in GPU environment, to save it with model.save(PATH). Then, after restarting the environment with only the available CPU (for example new Kaggle session), to reopen it with model.load(PATH).  This causes an error.

```python
RuntimeError: Attempting to deserialize object on a CUDA device but torch.cuda.is_available() is False. If you are running on a CPU-only machine, please use torch.load with map_location=torch.device('cpu') to map your storages to the CPU.
```

**Describe proposed solution**
Manage the GPU or CPU configuration in the load() function. This would allow running the trained models also on lighter environments like Raspberry.

**Describe potential alternatives**
Train only on CPU.

**Additional context**

Code:
```python
from darts.models import TFTModel
tft_model = TFTModel.load(WORK_DIR + "tft.pkl")
```

Output:
```python
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
/tmp/ipykernel_27/2667096778.py in <module>
      1 from darts.models import TFTModel
----> 2 tft_model = TFTModel.load(WORK_DIR + "tft_altitude.pkl")
      3 #tft_model = TFTModel.load_from_checkpoint(WORK_DIR + "tft_model") #load from last checkpoint, after hyper optim

/opt/conda/lib/python3.7/site-packages/darts/models/forecasting/torch_forecasting_model.py in load(path, **kwargs)
   1318         with open(path, "rb") as fin:
   1319             model: TorchForecastingModel = torch.load(
-> 1320                 fin, map_location=kwargs.get("map_location", None)
   1321             )
   1322 

/opt/conda/lib/python3.7/site-packages/torch/serialization.py in load(f, map_location, pickle_module, weights_only, **pickle_load_args)
    787                     except RuntimeError as e:
    788                         raise pickle.UnpicklingError(UNSAFE_MESSAGE + str(e)) from None
--> 789                 return _load(opened_zipfile, map_location, pickle_module, **pickle_load_args)
    790         if weights_only:
    791             try:

/opt/conda/lib/python3.7/site-packages/torch/serialization.py in _load(zip_file, map_location, pickle_module, pickle_file, **pickle_load_args)
   1129     unpickler = UnpicklerWrapper(data_file, **pickle_load_args)
   1130     unpickler.persistent_load = persistent_load
-> 1131     result = unpickler.load()
   1132 
   1133     torch._utils._validate_loaded_sparse_tensors()

/opt/conda/lib/python3.7/pickle.py in load(self)
   1086                     raise EOFError
   1087                 assert isinstance(key, bytes_types)
-> 1088                 dispatch[key[0]](self)
   1089         except _Stop as stopinst:
   1090             return stopinst.value

/opt/conda/lib/python3.7/pickle.py in load_binpersid(self)
   1127     def load_binpersid(self):
   1128         pid = self.stack.pop()
-> 1129         self.append(self.persistent_load(pid))
   1130     dispatch[BINPERSID[0]] = load_binpersid
   1131 

/opt/conda/lib/python3.7/site-packages/torch/serialization.py in persistent_load(saved_id)
   1099         if key not in loaded_storages:
   1100             nbytes = numel * torch._utils._element_size(dtype)
-> 1101             load_tensor(dtype, nbytes, key, _maybe_decode_ascii(location))
   1102 
   1103         return loaded_storages[key]

/opt/conda/lib/python3.7/site-packages/torch/serialization.py in load_tensor(dtype, numel, key, location)
   1081         # stop wrapping with TypedStorage
   1082         loaded_storages[key] = torch.storage.TypedStorage(
-> 1083             wrap_storage=restore_location(storage, location),
   1084             dtype=dtype)
   1085 

/opt/conda/lib/python3.7/site-packages/torch/serialization.py in default_restore_location(storage, location)
    213 def default_restore_location(storage, location):
    214     for _, _, fn in _package_registry:
--> 215         result = fn(storage, location)
    216         if result is not None:
    217             return result

/opt/conda/lib/python3.7/site-packages/torch/serialization.py in _cuda_deserialize(obj, location)
    180 def _cuda_deserialize(obj, location):
    181     if location.startswith('cuda'):
--> 182         device = validate_cuda_device(location)
    183         if getattr(obj, "_torch_load_uninitialized", False):
    184             with torch.cuda.device(device):

/opt/conda/lib/python3.7/site-packages/torch/serialization.py in validate_cuda_device(location)
    164 
    165     if not torch.cuda.is_available():
--> 166         raise RuntimeError('Attempting to deserialize object on a CUDA '
    167                            'device but torch.cuda.is_available() is False. '
    168                            'If you are running on a CPU-only machine, '

RuntimeError: Attempting to deserialize object on a CUDA device but torch.cuda.is_available() is False. If you are running on a CPU-only machine, please use torch.load with map_location=torch.device('cpu') to map your storages to the CPU.
```

**Comment by madtoinou** [comment] 2023-03-10 13:29
Hi,

This is a duplicate of #1624 which contains an example on how to load the model trained on GPU to a CPU to perform inference.

The documentation will be updated in order to include the explanations/example in this documentation [page](https://unit8co.github.io/darts/userguide/gpu_and_tpu_usage.html)

**Closed by madtoinou** 2023-03-10 13:29 UTC
Labels: triage

**Comment by adriengauche** [comment] 2023-03-10 13:33
OK. Thank you :-)
