### ISSUE TITLE
Manipulate Autoregressive Input

### ISSUE THREAD

**Issue by sandrohuni** [unit8co/darts#2289] opened 2024-03-19 09:28 UTC
Hi There, 

I am currently working on a TFT model. Right now I try to find a strategy to avoid overfitting. My plan is to smooth the input signal so the model doesn't learn noise and focus on the more general trend of the autoregressive signal.
Is there any way how I can only manipulate / smooth only the input signal of the target series? 

Thank you in advance!

**Comment by dennisbader** [comment] 2024-03-22 07:53
Hi @sandrohuni, you could use our [`MovingAverageFilter`](https://unit8co.github.io/darts/generated_api/darts.models.filtering.moving_average_filter.html#darts.models.filtering.moving_average_filter.MovingAverageFilter), or perform STL decomposition to smooth the signal with [`extract_trend_and_seasonality()`](https://unit8co.github.io/darts/generated_api/darts.utils.statistics.html#darts.utils.statistics.extract_trend_and_seasonality).

Does this answer your question?

**Comment by sandrohuni** [comment] 2024-03-22 09:41
Thank you for your fast answer @dennisbader . 
I was more thinking about only smoothing the autoregressive input for the TFT.
So if X is the target series. The model takes as an input X_smooth(t-input_chunk :t) and predicts y(t+1). But then for calculating the loss it uses the original Target series value X(t+1).  I am not sure if this approach makes sense and is possible to implement, but it would be interesting to see. 

Also on a different note: Is it possible to change the TFT (or other global models) so it only takes exogene covariates as an input to make it non-autoregressive. This would be very interesting in the field of hydrology for example, to predict discharge of ungauged rivers.

Thanks alot for taking the time to answer. Also I really enjoy working with darts - great tool :)

**Comment by madtoinou** [comment] 2024-03-27 08:01
Hi @sandrohuni,

For deep learning models such as `TFTModel`, I am not sure that smoothing the input features in order to forecast the "raw" target will actually help. You could eventually try to include the smoothed features as covariates and see if it actually help the model or not. If the results are better, the `RegressionModel` are capable of forecasting a target based on covariates only (example [here](https://unit8co.github.io/darts/examples/20-RegressionModel-examples.html#Using-only-covariates)).

Adding support for "covariates only" forecasting for the deep learning models is on the roadmap but the associated models' architecture modification are not straightforward. We want to take the time to make it cleanly. You can however avoid auto-regression by making sure that `output_chunk_length > n` where `n` is the number of steps forecasted when calling `predict()`.

**Comment by sandrohuni** [comment] 2024-03-27 15:54
Hi @madtoinou ,

Thank you very much for your answer. 
I know dirty adjusted the source code of the TFT to make it non autoregressive. I am looking forward to a clean implementation from you guys !

**Comment by madtoinou** [comment] 2024-03-28 08:35
Glad that you manage to find a workaround for your use-case.

Since this feature request is already tracked in #2151, I am closing this issue to limit duplicates.

**Closed by madtoinou** 2024-03-28 08:35 UTC
