### ISSUE TITLE
[BUG] Data Files Not Found

### ISSUE THREAD

**Issue by preksha017** [unit8co/darts#1973] opened 2023-08-30 00:00 UTC
**Describe the bug**
I am trying to run the transfer-learning.ipynb in google collab. But when i try to load the data by running cell number 2 I have an error. It seems that the location of the datafiles are wrong? 

**To Reproduce**
Link to the notebook: https://github.com/unit8co/darts/blob/master/examples/14-transfer-learning.ipynb

```
# Execute Cell 2
# Execute this cell once to download all three datasets
# Some datasets are are in pickle for simplicity and speed.
!curl -L https://github.com/unit8co/amld2022-forecasting-and-metalearning/blob/main/data/m3_dataset.xls\?raw\=true -o m3_dataset.xls
!curl -L https://github.com/unit8co/amld2022-forecasting-and-metalearning/blob/main/data/passengers.pkl\?raw\=true -o passengers.pkl
!curl -L https://github.com/unit8co/amld2022-forecasting-and-metalearning/blob/main/data/m4_monthly_scaled.pkl\?raw\=true -o m4_monthly_scaled.pkl
```

Can anyone show me where can i find the path to the datasets?

**Comment by dennisbader** [comment] 2023-08-30 06:14
Closing as this is a duplicate of #1948.

**Closed** 2023-08-30 06:14 UTC
Labels: bug, triage
